### ISSUE TITLE
Zoom & LINECALL UDP traffic not detecting in driver  but detected in nDPI reader

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#144]
@vel21ripn 

We recently moved from a Feb 2022 nDPI  flow_info-4 base code to the latest  flow_info-4 base code and looks like zoom UDP traffic detection is not working. We are able to detect TLS.Zoom which is TCP, DNS.Zoom. The same is true for LINECALL traffic

We ran the pcap with the nDPI reader and those detect the zoom traffic properly. The nDPI driver flows still show it as Unknown. I noticed that a similar issue was mentioned for Mining protocol back in May ( https://github.com/vel21ripn/nDPI/issues/132 ) and it was fixed.  Not sure if the UDP path has some issue

iptables command that we are using to track nDPI flows

iptables -t mangle -I FORWARD 1 -m ndpi --proto all -j ACCEPT

Was not sure if we needed any new command with the addition of --inprogress and --clevel. It did not seem necessary but just thought that I would check with you on the same.

Attached is the pcap 
[zoom_audio_call_new.zip](https://github.com/vel21ripn/nDPI/files/10032924/zoom_audio_call_new.zip)

root@kickseed:~/pcaps/nDPI/example# ./ndpiReader -i /root/pcaps/zoom_audio_call_new.pcap

Using nDPI (4.5.0-4208-dcff3ef8) [1 thread(s)]
Using libgcrypt version 1.8.6internal
Reading packets from pcap file /root/pcaps/zoom_audio_call_new.pcap...
Running thread 0...

nDPI Memory statistics:
        nDPI Memory (once):      36.86 KB
        Flow Memory (per flow):  912 B
        Actual Memory:           38.47 MB
        Peak Memory:             38.47 MB
        Setup Time:              27 msec
        Packet Processing Time:  71 msec

Traffic statistics:
        Ethernet bytes:        36331113      (includes ethernet CRC/IFC/trailer)
        Discarded bytes:       5056
        IP packets:            129901        of 130000 packets total
        IP bytes:              33213489      (avg pkt size 255 bytes)
        Unique flows:          168
        TCP Packets:           16572
        UDP Packets:           113299
        VLAN Packets:          0
        MPLS Packets:          0
        PPPoE Packets:         0
        Fragmented Packets:    0
        Max Packet size:       1480
        Packet Len < 64:       11328
        Packet Len 64-128:     33606
        Packet Len 128-256:    22172
        Packet Len 256-1024:   60096
        Packet Len 1024-1500:  2699
        Packet Len > 1500:     0
        nDPI throughput:       1.83 M pps / 3.81 Gb/sec
        Analysis begin:        17/Nov/2022 04:34:24
        Analysis end:          17/Nov/2022 05:02:29
        Traffic throughput:    77.08 pps / 168.41 Kb/sec
        Traffic duration:      1685.375 sec
        Guessed flow protos:   47
        DPI Packets (TCP):     822           (8.30 pkts/flow)
        DPI Packets (UDP):     240           (4.00 pkts/flow)
        DPI Packets (other):   9             (1.00 pkts/flow)
        Confidence: Unknown    42            (flows)
        Confidence: Match by port 1             (flows)
        Confidence: DPI (partial cache) 3             (flows)
        Confidence: DPI        122           (flows)

Detected protocols:
        Unknown              packets: 604           bytes: 57788         flows: 42
        DNS                  packets: 42            bytes: 5477          flows: 17
        HTTP                 packets: 42            bytes: 5594          flows: 4
        NTP                  packets: 2             bytes: 180           flows: 1
        SMBv1                packets: 2             bytes: 486           flows: 1
        OCSP                 packets: 10            bytes: 1703          flows: 2
        STUN                 packets: 40            bytes: 3440          flows: 2
        ICMP                 packets: 30            bytes: 3415          flows: 9
        TLS                  packets: 1093          bytes: 115821        flows: 8
        WindowsUpdate        packets: 112           bytes: 24938         flows: 8
        Zoom                 packets: 126525        bytes: 32368781      flows: 30
        Microsoft            packets: 1143          bytes: 500441        flows: 35
        Microsoft365         packets: 227           bytes: 121377        flows: 8
        Azure                packets: 29            bytes: 4048          flows: 1

Protocol statistics:
        Safe                        642903 bytes
        Acceptable                32512312 bytes
        Dangerous                      486 bytes
        Unrated                      57788 bytes

Risk stats [found 34 (20.2 %) flows with risks]:
        TLS (probably) Not Carrying HTTPS            5 [14.7 %]
        Unsafe Protocol                              1 [ 2.9 %]
        TLS Cert Validity Too Long                   4 [11.8 %]
        Error Code                                  12 [35.3 %]
        Unidirectional Traffic                      12 [35.3 %]

        NOTE: as one flow can have multiple risks set, the sum of the
              last column can exceed the number of flows with risks.

the fklow
root@kickseed:~/pcaps/nDPI/example# ./ndpiReader -i /root/pcaps/zoom_audio_call_new.pcap -v 2 -v 3 | grep -i "Zoom" | grep -v "DNS.Zoom" | grep -v "TLS.Zoom" | grep -v "91\/TLS"

Reading packets from pcap file /root/pcaps/zoom_audio_call_new.pcap...
        Zoom                 packets: 126525        bytes: 32368781      flows: 30

        1       UDP 172.8.0.100:52578 <-> 206.247.74.82:8801 [proto: 189/Zoom][IP: 189/Zoom][Encrypted][Confidence: DPI (partial cache)][cat: Video/26][62974 pkts/17269812 bytes <-> 43753 pkts/10633316 bytes][Goodput ratio: 85/83][1667.00 sec][bytes ratio: 0.238 (Upload)][IAT c2s/s2c min/avg/max/stddev: 0/0 25/22 1412/3751 78/140][Pkt Len c2s/s2c min/avg/max/stddev: 106/60 274/243 402/417 76/88][PLAIN TEXT (replace)][Plen Bins: 0,2,83,13,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        2       UDP 172.8.0.100:59254 <-> 206.247.74.82:8801 [proto: 189/Zoom][IP: 189/Zoom][Encrypted][Confidence: DPI (partial cache)][cat: Video/26][2208 pkts/1526665 bytes <-> 2099 pkts/1222923 bytes][Goodput ratio: 94/93][1665.25 sec][bytes ratio: 0.110 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 0/0 718/781 3748/7479 1356/1372][Pkt Len c2s/s2c min/avg/max/stddev: 119/60 691/583 1078/1078 463/472][PLAIN TEXT (replace)][Plen Bins: 0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        4       UDP 172.8.0.100:52579 <-> 206.247.74.82:8801 [proto: 189/Zoom][IP: 189/Zoom][Encrypted][Confidence: DPI (partial cache)][cat: Video/26][912 pkts/124242 bytes <-> 913 pkts/115607 bytes][Goodput ratio: 69/67][1665.27 sec][bytes ratio: 0.036 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 5/0 1831/1828 3751/7489 1615/1872][Pkt Len c2s/s2c min/avg/max/stddev: 69/60 136/127 185/133 17/10][PLAIN TEXT (replace)][Plen Bins: 13,0,63,20,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        56      UDP 172.8.0.100:10170 -> 206.247.73.253:3478 [proto: 78/STUN][IP: 189/Zoom][ClearText][Confidence: DPI][cat: Network/14][20 pkts/1720 bytes -> 0 pkts/0 bytes][Goodput ratio: 51/0][38.60 sec][bytes ratio: 1.000 (Upload)][IAT c2s/s2c min/avg/max/stddev: 2000/0 2032/0 2080/0 25/0][Pkt Len c2s/s2c min/avg/max/stddev: 86/0 86/0 86/0 0/0][Risk: ** Unidirectional Traffic **][Risk Score: 10][Risk Info: No server to client traffic][Plen Bins: 0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        57      UDP 172.8.0.100:10988 -> 206.247.73.253:3478 [proto: 78/STUN][IP: 189/Zoom][ClearText][Confidence: DPI][cat: Network/14][20 pkts/1720 bytes -> 0 pkts/0 bytes][Goodput ratio: 51/0][38.60 sec][bytes ratio: 1.000 (Upload)][IAT c2s/s2c min/avg/max/stddev: 2000/0 2032/0 2080/0 25/0][Pkt Len c2s/s2c min/avg/max/stddev: 86/0 86/0 86/0 0/0][Risk: ** Unidirectional Traffic **][Risk Score: 10][Risk Info: No server to client traffic][Plen Bins: 0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

Attached screenshot after we enabled the nDPI flows . The zoom traffic IP and port for this pcap and screenshot 
206.247.74.82:8801

![Screenshot (2543)](https://user-images.githubusercontent.com/52180175/202489004-bbaeebd2-928d-4157-9061-4944b63f10ea.png)

Please let me know if you require any additional information. 

We are going to retry this from the older Feb 2022 code with just an updated Zoom IP database to see if it works. Will get back to you what we find.

**Comment by vel21ripn** [comment]
Don't use "cat /proc/net/xt_ndpi/flows". Use "ndpi_flow_dump -m flows -s"
The command "cat /proc/net/xt_ndpi/flows" is reset to the counters, and streams with zero values are not displayed.
I have a tool that allows you to skip traffic via xt_ndpi and give it to ndpiReader in which the difference is visible for each packet. However, that this process is time-consuming.
Perhaps I can do this next week.

**Comment by sharonenoch** [comment]
Thanks for the quick response.. Will perform the test once more and use ndpi_flow_dump command to print the flows..  

We actually enabled the debug and flows in nDPI driver only after we saw that the firewall logs were not getting printed for the UDP flows of Zoom and Line. 

Is there any other debug that we can enable to get more logs, so that it would helpful in debugging this flow

**Comment by sharonenoch** [comment]
@vel21ripn 

So we did 2 tests yesterday

1) The latest code in flow_info-4. This did not detect zoom traffic. Below is the ndpi_flow_dump as you requested. You can check the destination port 8801 showing up as Unknown and not detected as Zoom traffic.  This code base had 308 IPs as part of the zoom ip database

```
bash-4.4# ./ndpi_flow_dump -m flows -s
TIME 1668781095
1668781095 1668781095 4 17 172.9.0.100 8184 25.34.217.37 46722 2352 0 21 0 I=6,5 SN=10.200.3.109,8184 P=Unknown
1668781055 1668781094 4 17 172.9.0.100 8184 144.195.16.253 3478 1440 0 20 0 I=6,5 SN=10.200.3.109,8184 P=stun
1668781055 1668781094 4 17 172.9.0.100 14465 144.195.16.253 3478 1440 0 20 0 I=6,5 SN=10.200.3.109,14465 P=stun
1668781045 1668781045 4 6 172.9.0.100 50107 118.214.137.233 80 399 395 4 3 I=6,5 SN=10.200.3.109,50107 P=http H=x1.c.lencr.org
1668781040 1668781042 4 6 172.9.0.100 50106 170.114.15.101 443 2752 5883 8 9 I=6,5 SN=10.200.3.109,50106 P=zoom,tls H=us04logfiles.zoom.us
1668781002 1668781092 4 17 172.9.0.100 63915 144.195.17.165 8801 8410 7404 74 76 I=6,5 SN=10.200.3.109,63915 P=Unknown
1668781001 1668781070 4 6 172.9.0.100 50101 3.19.157.213 443 9479 6502 13 14 I=6,5 SN=10.200.3.109,50101 P=zoom,tls H=evt-us.ds.corp.zoom.us
1668781001 1668781092 4 17 172.9.0.100 50596 144.195.17.165 8801 6674 5964 53 55 I=6,5 SN=10.200.3.109,50596 P=Unknown
1668781001 1668781095 4 17 172.9.0.100 50595 144.195.17.165 8801 5294019 4528460 5681 4211 I=6,5 SN=10.200.3.109,50595 P=Unknown
1668780999 1668781095 4 6 172.9.0.100 50098 144.195.17.165 443 84455 46214 386 421 I=6,5 SN=10.200.3.109,50098 P=zoom,tls H=zoomsjcar165mmr.sjc.zoom.us
1668780997 1668781090 4 6 172.9.0.100 50090 170.114.52.5 443 3907 18507 19 25 I=6,5 SN=10.200.3.109,50090 P=zoom,tls H=us05www3.zoom.us
1668780024 1668780973 4 6 172.9.0.100 50012 170.114.14.73 443 2950 6472 24 16 I=6,5 SN=10.200.3.109,50012 P=zoom,tls H=us04zpns.zoom.us
1668779968 1668781094 4 6 172.9.0.100 49984 170.114.15.169 443 22636 24268 145 120 I=6,5 SN=10.200.3.109,49984 P=zoom,tls H=us04xmpp1.zoom.us
1668779969 1668781091 4 6 172.9.0.100 49995 170.114.52.5 443 10596 16234 179 180 I=6,5 SN=10.200.3.109,49995 P=zoom,tls H=us05web.zoom.us
1668780029 1668781095 4 6 172.9.0.100 50014 170.114.52.5 443 9176 13560 167 168 I=6,5 SN=10.200.3.109,50014 P=zoom,tls H=us05www3.zoom.us
1668780029 1668781095 4 6 172.9.0.100 50015 170.114.52.5 443 9174 14039 167 168 I=6,5 SN=10.200.3.109,50015 P=zoom,tls H=us05www3.zoom.us
```


2)  We reverted back to a code base in Feb 2022(commit b15f1f6898af322f47b4ffe86feaafdf4349d1ff)  and Zoom was detected always in this code base.  Below are the ndpi_flow_dump logs which show the detected Zoom on port 8801. Here we did update all the latest zoom ips to get it to the same 308 ips via the ip_proto proc as that old code base had only 52 ips.

```
bash-4.4# ./ndpi_flow_dump -m flows -s
TIME 1668777895
1668777858 1668777894 4 17 172.8.0.100 11275 144.195.77.213 3478 1368 0 19 0 I=8,7 SN=10.200.3.122,11275 P=zoom,stun
1668777858 1668777894 4 17 172.8.0.100 9949 144.195.77.213 3478 1368 0 19 0 I=8,7 SN=10.200.3.122,9949 P=zoom,stun
1668777828 1668777894 4 6 172.8.0.100 50101 170.114.15.104 443 2795 5994 9 11 I=8,7 SN=10.200.3.122,50101 P=zoom,tls H=us04logfiles.zoom.us
1668777784 1668777893 4 17 172.8.0.100 59238 144.195.76.87 8801 9259 8283 81 83 I=8,7 SN=10.200.3.122,59238 P=zoom
1668777784 1668777858 4 6 172.8.0.100 50093 3.19.157.213 443 9479 6502 13 14 I=8,7 SN=10.200.3.122,50093 P=zoom,tls H=evt-us.ds.corp.zoom.us
1668777784 1668777893 4 17 172.8.0.100 65398 144.195.76.87 8801 7904 7104 63 65 I=8,7 SN=10.200.3.122,65398 P=zoom
1668777783 1668777895 4 17 172.8.0.100 65397 144.195.76.87 8801 4893142 4029779 4499 3769 I=8,7 SN=10.200.3.122,65397 P=zoom
1668777782 1668777895 4 6 172.8.0.100 50091 144.195.76.87 443 84812 47573 394 432 I=8,7 SN=10.200.3.122,50091 P=zoom,tls H=zoomsjccy87mmr.sjc.zoom.us
1668777779 1668777887 4 6 172.8.0.100 50083 170.114.52.5 443 3957 18470 20 24 I=8,7 SN=10.200.3.122,50083 P=zoom,tls H=us05www3.zoom.us
1668777747 1668777886 4 6 172.8.0.100 50077 170.114.52.5 443 3254 8047 19 19 I=8,7 SN=10.200.3.122,50077 P=zoom,tls H=us05www3.zoom.us
1668777747 1668777886 4 6 172.8.0.100 50076 170.114.52.5 443 3216 7157 18 18 I=8,7 SN=10.200.3.122,50076 P=zoom,tls H=us05www3.zoom.us
1668777699 1668777880 4 6 172.8.0.100 50066 54.192.219.252 443 2796 13547 16 20 I=8,7 SN=10.200.3.122,50066 P=zoom,tls H=marketplacecontent.zoom.us
1668777694 1668777876 4 6 172.8.0.100 50058 205.251.222.254 443 10167 540109 214 382 I=8,7 SN=10.200.3.122,50058 P=zoom,tls H=marketplacefront.zoom.us
1668777685 1668777895 4 6 172.8.0.100 50038 170.114.15.160 443 12876 16106 67 50 I=8,7 SN=10.200.3.122,50038 P=zoom,tls H=us04xmpp1.zoom.us
1668777684 1668777886 4 6 172.8.0.100 50035 170.114.52.5 443 4615 9736 24 23 I=8,7 SN=10.200.3.122,50035 P=zoom,tls H=us05web.zoom.us
1668777683 1668777821 4 6 172.8.0.100 50032 170.114.14.67 443 2300 6127 13 12 I=8,7 SN=10.200.3.122,50032 P=zoom,tls H=us04zpns.zoom.us
1668777682 1668777894 4 6 172.8.0.100 50029 170.114.52.5 443 13714 70520 54 75 I=8,7 SN=10.200.3.122,50029 P=zoom,tls H=us05web.zoom.us
```

**Comment by vel21ripn** [comment]
I fixed the bug due to missing ndpi_detection_giveup() call ce5cca1ec5972f8404ad66ec750a3c10968010fd.
It's not clear to me yet whether LRU zoom is being used.
I see in the output of ndpiReader confidence "DPI (partial cache)", and in /proc/net/xt_ndpi/flows confidence 2 "Match by IP". This needs to be dealt with.

**Comment by IvanNardi** [comment]
> It's not clear to me yet whether LRU zoom is being used.

@vel21ripn, speaking only of the upstream-nDPI, if you find the word "cache" in the confidence description it means some kind of LRU has been used.

**Comment by vel21ripn** [comment]
IMHO Commit d238ff6ad1715a640df62c7b47373293c8c136bd must be resolve this bug.

**Comment by vel21ripn** [comment]
Fixed cf017cc2fecee644d0b2ff633a17377f776d1505

**Comment by sharonenoch** [comment]
Thankyou for the quick fix. I will get back to you on Monday as I am currently travelling and don't have access to a setup to test the same..

**Comment by sharonenoch** [comment]
Zoom is detecting properly now..  Thankyou

Linecall seems to still have some issues.. Also I noticed you added 1 more fix from the initial fix.. Will add that in also in the testing..  Once I gather a proper pcap will keep you updated

**Comment by sharonenoch** [comment]
@vel21ripn  

For Line we are seeing the behavior to be not so consistent in the driver, but the ndpiReader is always detecting the same.
[lineVideoCall1.zip](https://github.com/vel21ripn/nDPI/files/10115196/lineVideoCall1.zip).. 

Attached pcap has a linecall where the UDP flow is from 172.8.0.100 to 147.92.169.21

Following filter can be used in Wireshark
ip.dst == 147.92.128.0/17 || ip.src == 147.92.128.0/17 

Below is the nDPI reader output.. The flow in question is below..

 UDP 172.8.0.100:63719 <-> 147.92.169.21:16673

```
root@kickseed:~/sharonnDPI/nDPI# ./example/ndpiReader -i /root/lineVideoCall1.pcap -v2 -v3

-----------------------------------------------------------
* NOTE: This is demo app to show *some* nDPI features.
* In this demo we have implemented only some basic features
* just to show you what you can do with the library. Feel
* free to extend it and send us the patches for inclusion
------------------------------------------------------------

Using nDPI (4.5.0-3885-2d6403c7) [1 thread(s)]
Using libgcrypt version 1.8.6internal
Reading packets from pcap file /root/lineVideoCall1.pcap...
Running thread 0...

nDPI Memory statistics:
        nDPI Memory (once):      36.59 KB
        Flow Memory (per flow):  872 B
        Actual Memory:           13.43 MB
        Peak Memory:             13.43 MB
        Setup Time:              48 msec
        Packet Processing Time:  11 msec

Traffic statistics:
        Ethernet bytes:        7902540       (includes ethernet CRC/IFC/trailer)
        Discarded bytes:       0
        IP packets:            10000         of 10000 packets total
        IP bytes:              7662540       (avg pkt size 766 bytes)
        Unique flows:          6
        TCP Packets:           352
        UDP Packets:           9648
        VLAN Packets:          0
        MPLS Packets:          0
        PPPoE Packets:         0
        Fragmented Packets:    0
        Max Packet size:       1480
        Packet Len < 64:       319
        Packet Len 64-128:     1371
        Packet Len 128-256:    1000
        Packet Len 256-1024:   6179
        Packet Len 1024-1500:  1131
        Packet Len > 1500:     0
        nDPI throughput:       876.50 K pps / 5.16 Gb/sec
        Analysis begin:        29/Nov/2022 05:04:05
        Analysis end:          29/Nov/2022 05:07:07
        Traffic throughput:    54.72 pps / 337.81 Kb/sec
        Traffic duration:      182.760 sec
        Guessed flow protos:   0
        DPI Packets (TCP):     27            (6.75 pkts/flow)
        DPI Packets (UDP):     28            (14.00 pkts/flow)
        Confidence: DPI        6             (flows)


Detected protocols:
        Line                 packets: 352           bytes: 156269        flows: 4
        LineCall             packets: 9648          bytes: 7506271       flows: 2


Protocol statistics:
        Acceptable                 7662540 bytes

Risk stats [found 4 (66.7 %) flows with risks]:
        TLS (probably) Not Carrying HTTPS            4 [100.0 %]

        NOTE: as one flow can have multiple risks set, the sum of the
              last column can exceed the number of flows with risks.



JA3C/JA3S Host Stats:
                IP                       JA3C                               JA3S
        1       172.8.0.100              ca75ea4a95a9164cc96e372d7d075183
        2       172.8.0.100              9f65608af90d890731d8863bc910d713
        3       147.92.242.232                                              567bb420d39046dbfd1f68b558d86382
        4       147.92.165.68                                               15af977ce25de452b96affa2addb1036
        5       147.92.191.86                                               e35df3e00ca4ef31d42b34bebaa2f86e

IP/JA3 Distribution:
                JA3                                     IP
        1       JA3C ca75ea4a95a9164cc96e372d7d075183   172.8.0.100
        2       JA3C 9f65608af90d890731d8863bc910d713   172.8.0.100
        3       JA3S 567bb420d39046dbfd1f68b558d86382   147.92.242.232
        4       JA3S 15af977ce25de452b96affa2addb1036   147.92.165.68
        5       JA3S e35df3e00ca4ef31d42b34bebaa2f86e   147.92.191.86


        1       UDP 172.8.0.100:63719 <-> 147.92.169.21:16673 [proto: 316/LineCall][IP: 315/Line][Encrypted][Confidence: DPI][cat: VoIP/10][7730 pkts/6828431 bytes <-> 1908 pkts/675896 bytes][Goodput ratio: 95/88][49.38 sec][bytes ratio: 0.820 (Upload)][IAT c2s/s2c min/avg/max/stddev: 0/0 4/18 809/9153 13/262][Pkt Len c2s/s2c min/avg/max/stddev: 62/62 883/354 1098/1089 295/340][Plen Bins: 1,16,31,14,9,10,2,0,0,0,1,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        2       TCP 172.8.0.100:59382 <-> 147.92.165.68:443 [proto: 91.315/TLS.Line][IP: 315/Line][Encrypted][Confidence: DPI][cat: Chat/9][112 pkts/13678 bytes <-> 159 pkts/116839 bytes][Goodput ratio: 56/92][180.21 sec][Hostname/SNI: gwz.line.naver.jp][bytes ratio: -0.790 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 2133/1262 59585/59585 9257/7420][Pkt Len c2s/s2c min/avg/max/stddev: 54/60 122/735 1494/1514 162/679][Risk: ** TLS (probably) Not Carrying HTTPS **][Risk Score: 10][Risk Info: No ALPN][TLSv1.3][JA3C: 9f65608af90d890731d8863bc910d713][JA3S: 15af977ce25de452b96affa2addb1036][Firefox][Cipher: TLS_AES_256_GCM_SHA384][Plen Bins: 0,17,11,7,3,4,1,2,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,0,0]
        3       TCP 172.8.0.100:59398 <-> 147.92.191.86:443 [proto: 91.315/TLS.Line][IP: 315/Line][Encrypted][Confidence: DPI][cat: Chat/9][11 pkts/2747 bytes <-> 12 pkts/7378 bytes][Goodput ratio: 78/91][8.43 sec][Hostname/SNI: lan.line.me][bytes ratio: -0.457 (Download)][IAT c2s/s2c min/avg/max/stddev: 1/0 154/118 278/239 118/118][Pkt Len c2s/s2c min/avg/max/stddev: 54/60 250/615 571/1514 235/574][Risk: ** TLS (probably) Not Carrying HTTPS **][Risk Score: 10][Risk Info: No ALPN][TLSv1.2][JA3C: ca75ea4a95a9164cc96e372d7d075183][ServerNames: *.line.me,line.me][JA3S: e35df3e00ca4ef31d42b34bebaa2f86e][Issuer: C=BE, O=GlobalSign nv-sa, CN=GlobalSign RSA OV SSL CA 2018][Subject: C=JP, ST=Tokyo-to, L=Shinjuku-ku, O=LINE Corporation, CN=*.line.me][Certificate SHA-1: 72:BB:C0:78:1C:91:A0:DF:F3:49:32:BC:6F:56:F6:BE:AE:48:14:03][Firefox][Validity: 2022-08-08 08:36:05 - 2023-09-09 08:36:04][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384][Plen Bins: 7,0,0,7,0,0,0,7,7,0,0,7,0,0,0,21,7,0,7,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,0,0]
        4       TCP 172.8.0.100:59406 <-> 147.92.242.232:443 [proto: 91.315/TLS.Line][IP: 315/Line][Encrypted][Confidence: DPI][cat: Chat/9][15 pkts/3997 bytes <-> 19 pkts/5157 bytes][Goodput ratio: 79/79][33.60 sec][Hostname/SNI: uts-front.line-apps.com][bytes ratio: -0.127 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 1/0 2988/202 29999/1100 8544/315][Pkt Len c2s/s2c min/avg/max/stddev: 54/60 266/271 627/1514 232/435][Risk: ** TLS (probably) Not Carrying HTTPS **][Risk Score: 10][Risk Info: No ALPN][TLSv1.2][JA3C: ca75ea4a95a9164cc96e372d7d075183][ServerNames: *.line-apps.com,line-apps.com][JA3S: 567bb420d39046dbfd1f68b558d86382][Issuer: C=BE, O=GlobalSign nv-sa, CN=GlobalSign RSA OV SSL CA 2018][Subject: C=JP, ST=Tokyo-to, L=Shinjuku-ku, O=LINE Corporation, CN=*.line-apps.com][Certificate SHA-1: C8:EB:57:1A:17:32:27:8D:C4:3A:D3:27:58:FF:64:A8:5C:FE:88:51][Firefox][Validity: 2022-10-13 17:31:02 - 2023-11-14 17:31:01][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384][Plen Bins: 5,11,5,0,0,16,5,0,5,16,0,0,0,0,0,0,11,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0]
        5       TCP 172.8.0.100:59379 <-> 147.92.191.86:443 [proto: 91.315/TLS.Line][IP: 315/Line][Encrypted][Confidence: DPI][cat: Chat/9][15 pkts/1929 bytes <-> 9 pkts/4544 bytes][Goodput ratio: 57/89][123.87 sec][Hostname/SNI: lan.line.me][bytes ratio: -0.404 (Download)][IAT c2s/s2c min/avg/max/stddev: 1/0 10157/1248 88558/7000 23990/2575][Pkt Len c2s/s2c min/avg/max/stddev: 54/60 129/505 571/1514 166/569][Risk: ** TLS (probably) Not Carrying HTTPS **][Risk Score: 10][Risk Info: No ALPN][TLSv1.2][JA3C: ca75ea4a95a9164cc96e372d7d075183][ServerNames: *.line.me,line.me][JA3S: e35df3e00ca4ef31d42b34bebaa2f86e][Issuer: C=BE, O=GlobalSign nv-sa, CN=GlobalSign RSA OV SSL CA 2018][Subject: C=JP, ST=Tokyo-to, L=Shinjuku-ku, O=LINE Corporation, CN=*.line.me][Certificate SHA-1: 72:BB:C0:78:1C:91:A0:DF:F3:49:32:BC:6F:56:F6:BE:AE:48:14:03][Firefox][Validity: 2022-08-08 08:36:05 - 2023-09-09 08:36:04][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384][Plen Bins: 11,0,0,11,0,0,0,11,11,0,0,0,0,0,11,0,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,0]
        6       UDP 172.8.0.100:54010 <-> 147.92.169.21:16673 [proto: 316/LineCall][IP: 315/Line][Encrypted][Confidence: DPI][cat: VoIP/10][5 pkts/898 bytes <-> 5 pkts/1046 bytes][Goodput ratio: 77/80][8.08 sec][bytes ratio: -0.076 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 1999/1999 2011/2011 2044/2043 19/19][Pkt Len c2s/s2c min/avg/max/stddev: 174/198 180/209 202/254 11/22][Plen Bins: 0,0,0,0,80,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]


Source Ports Stats:
         1      Port 63719      [1 IP address(es)/1 flows/7730 pkts/6828431 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%

         2      Port 59382      [1 IP address(es)/1 flows/112 pkts/13678 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%

         3      Port 59406      [1 IP address(es)/1 flows/15 pkts/3997 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%

         4      Port 59379      [1 IP address(es)/1 flows/15 pkts/1929 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%

         5      Port 59398      [1 IP address(es)/1 flows/11 pkts/2747 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%

         6      Port 54010      [1 IP address(es)/1 flows/5 pkts/898 bytes]
                Top IP Stats:
                172.8.0.100                          ~ 100.00%


Destination Ports Stats:
         1      Port 16673      [1 IP address(es)/2 flows/1913 pkts/676942 bytes]
                Top IP Stats:
                147.92.169.21                        ~ 100.00%

         2      Port   443      [3 IP address(es)/4 flows/199 pkts/133918 bytes]
                Top IP Stats:
                147.92.191.86                        ~ 50.00%
                147.92.242.232                       ~ 25.00%
                147.92.165.68                        ~ 25.00%


```

The driver ndpi_flow_dump output is as  follows

```
bash-4.4# ./ndpi_flow_dump -m flows -s
TIME 1669716380
1669716378 1669716379 4 17 172.8.0.100 63719 147.92.169.21 16673 10195 10054 19 19 I=8,7 SN=10.200.3.141,63719 P=Unknown
1669716369 1669716373 4 6 172.8.0.100 59406 147.92.242.232 443 3747 4692 14 16 I=8,7 SN=10.200.3.141,59406 P=line,tls H=uts-front.line-apps.com
1669716369 1669716369 4 17 172.8.0.100 63705 1.1.1.1 53 69 85 1 1 I=8,7 SN=10.200.3.141,63705 P=line,dns H=uts-front.line-apps.com
1669716350 1669716350 4 6 172.8.0.100 59401 23.50.244.182 443 1267 5166 7 9 I=8,7 SN=10.200.3.141,59401 P=line,tls H=desktop.line-scdn.net
1669716349 1669716350 4 17 172.8.0.100 61358 1.1.1.1 53 67 203 1 1 I=8,7 SN=10.200.3.141,61358 P=line,dns H=desktop.line-scdn.net
1669716341 1669716350 4 6 172.8.0.100 59398 147.92.191.86 443 2593 7118 11 10 I=8,7 SN=10.200.3.141,59398 P=line,tls H=lan.line.me
1669716341 1669716341 4 17 172.8.0.100 51788 1.1.1.1 53 57 129 1 1 I=8,7 SN=10.200.3.141,51788 P=line,dns H=lan.line.me
1669716245 1669716376 4 6 172.8.0.100 59382 147.92.165.68 443 11996 113651 110 143 I=8,7 SN=10.200.3.141,59382 P=line,tls H=gwz.line.naver.jp
```

```
bash-4.4# ./ndpi_flow_dump -m flows -s
TIME 1669716421
1669716378 1669716421 4 17 172.8.0.100 63719 147.92.169.21 16673 5540436 391891 6389 1400 I=8,7 SN=10.200.3.141,63719 P=Unknown
1669716369 1669716403 4 6 172.8.0.100 59406 147.92.242.232 443 3787 4803 15 18 I=8,7 SN=10.200.3.141,59406 P=line,tls H=uts-front.line-apps.com
1669716369 1669716369 4 17 172.8.0.100 63705 1.1.1.1 53 69 85 1 1 I=8,7 SN=10.200.3.141,63705 P=line,dns H=uts-front.line-apps.com
1669716350 1669716411 4 6 172.8.0.100 59401 23.50.244.182 443 1387 5277 10 11 I=8,7 SN=10.200.3.141,59401 P=line,tls H=desktop.line-scdn.net
1669716349 1669716350 4 17 172.8.0.100 61358 1.1.1.1 53 67 203 1 1 I=8,7 SN=10.200.3.141,61358 P=line,dns H=desktop.line-scdn.net
1669716341 1669716350 4 6 172.8.0.100 59398 147.92.191.86 443 2593 7118 11 10 I=8,7 SN=10.200.3.141,59398 P=line,tls H=lan.line.me
1669716341 1669716341 4 17 172.8.0.100 51788 1.1.1.1 53 57 129 1 1 I=8,7 SN=10.200.3.141,51788 P=line,dns H=lan.line.me
1669716245 1669716376 4 6 172.8.0.100 59382 147.92.165.68 443 11996 113651 110 143 I=8,7 SN=10.200.3.141,59382 P=line,tls H=gwz.line.naver.jp
```

Please let me know if there is any other output that we can provide to help debug the same

**Comment by vel21ripn** [comment]
I will try to fix this problem. An error can be reproduced on a short fragment:
````
tcpdump  -r lineVideoCall1.pcap -c 23 -w lineVideoCall2.pcap udp
````

**Comment by vel21ripn** [comment]
We need change parameters for module xt_ndpi "max_unk_udp=32 max_unk_tcp=32 max_unk_other=32"
You can change options via sysfs
```
echo 32 >/sys/module/xt_ndpi/parameters/max_unk_udp
```

**Comment by sharonenoch** [comment]
Thanks @vel21ripn . We tested this change and it is detecting Linecall now.. I feel based on our earlier tests also, analyzing 32 packets should be sufficient to detect line.  I am marking this issue as fixed

```
bash-4.4# ./ndpi_flow_dump -m flows -s | grep 192.168.64.100
1669975118 1669975782 4 17 192.168.64.100 56121 147.92.169.18 24273 22580643 11854103 46984 48696 I=8,7 SN=10.200.3.42,56121 P=linecall
1669975066 1669975736 4 6 192.168.64.100 50010 147.92.165.68 443 20168 144609 177 225 I=8,4 SN=100.64.236.70,50010 P=line,tls H=gwz.line.naver.jp
1669975020 1669975782 4 6 192.168.64.100 49951 203.17.244.49 443 6075 6900 150 150 I=8,7 SN=10.200.3.42,49951 P=tls
```

**Comment by sharonenoch** [comment]
@vel21ripn So we were retesting zoom and it stopped getting detected, while nDPIreader shows it properly in all the pcaps.

We have narrowed it down to when we add the 'max_unk_udp=32 max_unk_tcp=32 max_unk_other=32" during driver load time to increase the packets which are traversed for the line, is when zoom stops getting detected.  Can you please check..

We performed 4 runs.. Below are the results

modprobe xt_ndpi max_unk_udp=32 max_unk_tcp=32 max_unk_other=32 ndpi_enable_flow=1 ndpi_flow_limit=500  -> Does not detect zoom. it detect Line fine.

Run 2 -> modprobe xt_ndpi max_unk_udp=32 max_unk_tcp=32 max_unk_other=32  -> Does not detect zoom. it detect Line fine.

Run 3 -> modprobe xt_ndpi ndpi_enable_flow=1 ndpi_flow_limit=500 -> It detects zoom but does not detect Line

Run 4 -> modprobe xt_ndpi -> It detects zoom but does not detect Line

We also checked with the latest tree also which had a commit for improved zoom detection.

**Comment by vel21ripn** [comment]
Can you give me a sample of the traffic that shows the error?

**Comment by sharonenoch** [comment]
[zoom_new.zip](https://github.com/vel21ripn/nDPI/files/10385184/zoom_new.zip)

Attached pcap. I trimmed the tcpdump based on the following filter ip.src == 144.195.22.81 || ip.dst == 144.195.22.81 and captured the first 10000 packets as the call was more than 10 minutes long.. Hopefully the behavior remains the same when simulated with those parameters (max_unk_udp=32 max_unk_tcp=32 max_unk_other=32).. if not we will capture one more dump.

Below is the ndpi reader output.

``` ./ndpiReader -i zoom_new.pcap -v 2 -v 3

-----------------------------------------------------------
* NOTE: This is demo app to show *some* nDPI features.
* In this demo we have implemented only some basic features
* just to show you what you can do with the library. Feel
* free to extend it and send us the patches for inclusion
------------------------------------------------------------

Using nDPI (4.5.0-4208-dcff3ef8) [1 thread(s)]
Using libgcrypt version 1.8.6internal
Reading packets from pcap file zoom_new.pcap...
Running thread 0...

nDPI Memory statistics:
        nDPI Memory (once):      36.86 KB
        Flow Memory (per flow):  912 B
        Actual Memory:           8.25 MB
        Peak Memory:             8.25 MB
        Setup Time:              71 msec
        Packet Processing Time:  6 msec

Traffic statistics:
        Ethernet bytes:        3839694       (includes ethernet CRC/IFC/trailer)
        Discarded bytes:       0
        IP packets:            7056          of 7056 packets total
        IP bytes:              3670350       (avg pkt size 520 bytes)
        Unique flows:          8
        TCP Packets:           1217
        UDP Packets:           5826
        VLAN Packets:          0
        MPLS Packets:          0
        PPPoE Packets:         0
        Fragmented Packets:    0
        Max Packet size:       1480
        Packet Len < 64:       909
        Packet Len 64-128:     1974
        Packet Len 128-256:    698
        Packet Len 256-1024:   1063
        Packet Len 1024-1500:  2412
        Packet Len > 1500:     0
        nDPI throughput:       1.14 M pps / 4.63 Gb/sec
        Analysis begin:        05/Jan/2023 11:56:55
        Analysis end:          05/Jan/2023 12:01:07
        Traffic throughput:    28.02 pps / 119.13 Kb/sec
        Traffic duration:      251.798 sec
        Guessed flow protos:   6
        DPI Packets (TCP):     6             (6.00 pkts/flow)
        DPI Packets (UDP):     118           (19.67 pkts/flow)
        DPI Packets (other):   1             (1.00 pkts/flow)
        Confidence: DPI (partial cache) 6             (flows)
        Confidence: DPI        2             (flows)


Detected protocols:
        ICMP                 packets: 13            bytes: 1134          flows: 1
        Zoom                 packets: 7043          bytes: 3669216       flows: 7
```

**Comment by vel21ripn** [comment]
Please check commit 59c0a10eaef36067b1655e58154badab393764e8

**Comment by sharonenoch** [comment]
Thankyou... Will check with that fix

**Comment by sharonenoch** [comment]
Thanks @vel21ripn .. We tested this and it detects both zoom and linecall. Closing the issue
